#! /bin/sh

TF_OUTPUT_JSON=$(terraform output --json)
#echo $TF_OUTPUT_JSON
MASTER_IP=$(echo $TF_OUTPUT_JSON | jq -r .master_ip.value)
#echo "$MASTER_IP"
WORKER_IPS="$(echo $TF_OUTPUT_JSON | jq -r .worker_ips.value[])"
#echo "$WORKER_IPS"

cat <<-EOF
# Generated by $(realpath "$0") at $(date)

[master]
master1 ansible_ssh_host=$MASTER_IP

[worker]
$WORKER_IPS

[master:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[worker:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
EOF
